# Generated by Django 4.2.30 on 2026-06-24 13:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo permite letras, números y espacios (3-100 caracteres).', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s]{3,100}$')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.RegexValidator(message='Ingrese un precio válido (ej: 15000 o 15000.00).', regex='^\\d+(\\.\\d{1,2})?$'), django.core.validators.MinValueValidator(0.01)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('ingredientes', models.TextField(blank=True, help_text='Separar por comas', null=True)),
                ('tiempo_preparacion', models.PositiveIntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.RegexValidator(message='El stock solo permite números enteros positivos.', regex='^[0-9]+$')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación'), ('cambio_precio', 'Cambio de Precio'), ('cambio_stock', 'Cambio de Stock')], max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_p_categor_17b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='productos_p_estado_ec69d1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['disponibilidad'], name='productos_p_disponi_7fa91f_idx'),
        ),
    ]
